### ISSUE TITLE
Implement Builders RFC 0008: Jammy Builders

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/builder-jammy-buildpackless-full#1]
## Describe the Enhancement

A set of stacks based on the Ubuntu 2022.04 LTS (Jammy Jellyfish) will be maintained by Paketo, per stacks [RFC 0004](https://github.com/paketo-buildpacks/rfcs/blob/da3339d071ffed23c3cd1b374a6bfcefdea7ac70/text/stacks/0004-jammy-jellyfish.md). Paketo plans to distribute builders based on these stacks, per [Builders RFC 0008](https://github.com/paketo-buildpacks/rfcs/blob/main/text/builders/0008-jammy-builders.md).

## Possible Solution

- [ ] `builder.toml` that uses Jammy Full stack and doesn't include any buildpacks
- [ ] smoke tests
- [ ] full repo automation (see https://github.com/paketo-buildpacks/github-config/tree/main/builder)

## Motivation

The RFC has been accepted. Time to implement!

**Comment by ForestEckhardt** [comment]
Jammy full stack is live.
